// flow-typed signature: d7484d17b86f4da6b56034998154e4e3
// flow-typed version: <<STUB>>/babel-plugin-react-autoprefix_v^0.2.6/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-autoprefix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-autoprefix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-react-autoprefix/index' {
  declare module.exports: $Exports<'babel-plugin-react-autoprefix'>;
}
declare module 'babel-plugin-react-autoprefix/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-autoprefix'>;
}
