// flow-typed signature: ff9282ff69d2bab82a9e7d09961614a9
// flow-typed version: <<STUB>>/eslint-plugin-mocha_v^2.2.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-mocha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-mocha/lib/rules/handle-done-callback' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mocha/lib/rules/no-exclusive-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mocha/lib/rules/no-global-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mocha/lib/rules/no-pending-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mocha/lib/rules/no-skipped-tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mocha/lib/rules/no-synchronous-tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-mocha/index' {
  declare module.exports: $Exports<'eslint-plugin-mocha'>;
}
declare module 'eslint-plugin-mocha/index.js' {
  declare module.exports: $Exports<'eslint-plugin-mocha'>;
}
declare module 'eslint-plugin-mocha/lib/rules/handle-done-callback.js' {
  declare module.exports: $Exports<'eslint-plugin-mocha/lib/rules/handle-done-callback'>;
}
declare module 'eslint-plugin-mocha/lib/rules/no-exclusive-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-mocha/lib/rules/no-exclusive-tests'>;
}
declare module 'eslint-plugin-mocha/lib/rules/no-global-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-mocha/lib/rules/no-global-tests'>;
}
declare module 'eslint-plugin-mocha/lib/rules/no-pending-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-mocha/lib/rules/no-pending-tests'>;
}
declare module 'eslint-plugin-mocha/lib/rules/no-skipped-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-mocha/lib/rules/no-skipped-tests'>;
}
declare module 'eslint-plugin-mocha/lib/rules/no-synchronous-tests.js' {
  declare module.exports: $Exports<'eslint-plugin-mocha/lib/rules/no-synchronous-tests'>;
}
