// flow-typed signature: 08b1e39eb7f66b68ba521fa4f51bdab0
// flow-typed version: <<STUB>>/gulp-stylus_v^2.3.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-stylus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-stylus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-stylus/examples/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-stylus/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-stylus/examples/gulpfile.js' {
  declare module.exports: $Exports<'gulp-stylus/examples/gulpfile'>;
}
declare module 'gulp-stylus/index' {
  declare module.exports: $Exports<'gulp-stylus'>;
}
declare module 'gulp-stylus/index.js' {
  declare module.exports: $Exports<'gulp-stylus'>;
}
declare module 'gulp-stylus/test/main.js' {
  declare module.exports: $Exports<'gulp-stylus/test/main'>;
}
