// flow-typed signature: e62c71961408407fe6c1cbb3cf2a4f45
// flow-typed version: <<STUB>>/postcss-modules_v^0.5.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-modules/build/behaviours' {
  declare module.exports: any;
}

declare module 'postcss-modules/build/generateScopedName' {
  declare module.exports: any;
}

declare module 'postcss-modules/build/index' {
  declare module.exports: any;
}

declare module 'postcss-modules/build/saveJSON' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-modules/build/behaviours.js' {
  declare module.exports: $Exports<'postcss-modules/build/behaviours'>;
}
declare module 'postcss-modules/build/generateScopedName.js' {
  declare module.exports: $Exports<'postcss-modules/build/generateScopedName'>;
}
declare module 'postcss-modules/build/index.js' {
  declare module.exports: $Exports<'postcss-modules/build/index'>;
}
declare module 'postcss-modules/build/saveJSON.js' {
  declare module.exports: $Exports<'postcss-modules/build/saveJSON'>;
}
