// flow-typed signature: 4fe57df8e5188baa0cb985037addd5eb
// flow-typed version: <<STUB>>/postcss-functions_v^2.1.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-functions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-functions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-functions/src/index' {
  declare module.exports: any;
}

declare module 'postcss-functions/src/promiseHelpers' {
  declare module.exports: any;
}

declare module 'postcss-functions/src/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-functions/src/index.js' {
  declare module.exports: $Exports<'postcss-functions/src/index'>;
}
declare module 'postcss-functions/src/promiseHelpers.js' {
  declare module.exports: $Exports<'postcss-functions/src/promiseHelpers'>;
}
declare module 'postcss-functions/src/transform.js' {
  declare module.exports: $Exports<'postcss-functions/src/transform'>;
}
