// flow-typed signature: a4c4f7770f1edcccf7a1345c968cb9fe
// flow-typed version: <<STUB>>/react-progress-button_vgit+https://github.com/aleksei0807/react-progress-button.git/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-progress-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-progress-button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-progress-button/lib/index' {
  declare module.exports: any;
}

declare module 'react-progress-button/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-progress-button/lib/index.js' {
  declare module.exports: $Exports<'react-progress-button/lib/index'>;
}
declare module 'react-progress-button/src/index.js' {
  declare module.exports: $Exports<'react-progress-button/src/index'>;
}
